// https://hardcoreselfhelp.libsyn.com/page/14/size/25
export default [
    {   "podcastId":"POD1",
        "artist":"Duff the Psych",
        "podcastTitle":"The Hardcore Self Help Podcast with Duff the Psych",
        "podcastThumbnail":"https://m.media-amazon.com/images/I/61i6E3djuUL._SL500_.jpg",
        "podcastEpisodes":[
            {
                "episodeNumber":1,
                "episodeTitle":"The Hardcore Self Help Podcast Episode 1",
                "episodeDescription":" First question: Is seven medications for anxiety and depression just crazy? Second question: What's the point of getting extensive testing for dementia? Third question: How to help a family member who has slid back into depression? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_1.mp3",
                "isCompleted":true,
            },
            {
                "episodeNumber":2,
                "episodeTitle":"Anger, Low Cost Resources, and Cigarettes",
                "episodeDescription":"In this episode, I make a few short announcements and then take a few awesome questions from listeners.First question: How to avoid explosive anger like my dad? Second question: How can I find services without insurance? Third question: Can quitting cigarettes lead to depression?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_2.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":3,
                "episodeTitle":"Anxiety Awareness, Panic Attacks, and Pets",
                "episodeDescription":"In this episode I ask you for your reviews and take some wonderful listener questions.First question: What if I am too aware of my anxiety? Second question: How to deal with panic attacks aside from medication?. Third question:Are pets actually beneficial to your mental health?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_3.mp3",
                "isCompleted":true,
            },
            {
                "episodeNumber":4,
                "episodeTitle":"Ryan on Male Depression, Body Image, and Gaming",
                "episodeDescription":"This is an awesome episode. I welcome my very first guest, Ryan, to the show. He is a buddy of mine from college and we talk about his experiences with depression. I am really happy with this interview because Ryan was so willing to talk candidly and openly about things that just don't seem to be talked about enough in every day life. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_4.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":5,
                "episodeTitle":"Social Anxiety, Recovering from Sexual Abuse, and Migraines",
                "episodeDescription":"First question: What can I do about my social anxiety when I have to interact with important people? Second question: Is there hope for me in recovering from my sexual abuse? Third question: Should I worry about hallucinations that come along with my migraines?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_5.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":6,
                "episodeTitle":"Mike Billstrom on Unexpected Mentors, Overcoming Adve...",
                "episodeDescription":"This episode features a great interview with a new friend, Mike Billstrom from http://theartofgrowth.com. Mike talks about how he had to grow up very quickly to overcome an extremely turbulent upbringing. He found himself in the throes of depression, anxiety, and terrible self-esteem. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_6.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":7,
                "episodeTitle":" Spouse with Depression, Breaking Down Walls, and Getting Over a Breakup",
                "episodeDescription":"First question: How to cope with a severely depressed spouse when you are prone to depression and anxiety yourself? Second question: How to break down the walls that prevent you from truly connecting with other people? Third question: How to 'get over' the loss of a relationship? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_7.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":8,
                "episodeTitle":"Lindsay Istace on Rage Yoga",
                "episodeDescription":"In this episode, I interview Lindsay Istace who is the creator or Rage Yoga (http://rageyoga.com). You have probably heard of Rage Yoga already since it blew up on the news and social media. It is an alternative approach to yoga that strips away the BS and encourages you to release your inner tension through the use of a few choice expletives and 'fist unicorn' additions to your normal yoga poses. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_8.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":9,
                "episodeTitle":"Touch in Therapy, Bringing up Baggage, and Changing Therapists",
                "episodeDescription":"First question: Is it okay to hug your therapist? Second question: WWhen should I bring up my bumpy relationship history with my new partner? Third question:  Should I change therapists?  ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_9.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":10,
                "episodeTitle":"Shannon McFarlin on Talkspace and Internet Therapy",
                "episodeDescription":"This is a super interesting interview! I got a chance to speak to Shannon McFarlin who is a therapist from Talkspace. Talkspace is one of the biggest platforms for internet-based psychotherapy for an affordable price. I do private online therapy, but I was not familiar with larger platforms like Talkspace, so this was totally enlightening for me. I walked away with a very positive impression.",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_10.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":11,
                "episodeTitle":"Impostor Syndrome, Codependency, and Upset Stomach",
                "episodeDescription":"First question:How to overcome the impostor syndrome (feeling like you are a fraud)? Second question: How to have good relationships when you have intense, codependent tendencies? Third question:What you can do about upset stomach with anxiety? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_11.mp3",
                "isCompleted":false,
            },
        ]

    },
    {   "podcastId":"POD2",
        "artist":"Duff the Psych",
        "podcastTitle":"Feeling Good",
        "podcastThumbnail":"https://i.scdn.co/image/08c9590cacd8bb0391913cf89e9174fc254ee12a",
        "podcastEpisodes":[
            {
                "episodeNumber":1,
                "episodeTitle":"The Hardcore Self Help Podcast Episode 1",
                "episodeDescription":" First question: Is seven medications for anxiety and depression just crazy? Second question: What's the point of getting extensive testing for dementia? Third question: How to help a family member who has slid back into depression? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_1.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":2,
                "episodeTitle":"Anger, Low Cost Resources, and Cigarettes",
                "episodeDescription":"In this episode, I make a few short announcements and then take a few awesome questions from listeners.First question: How to avoid explosive anger like my dad? Second question: How can I find services without insurance? Third question: Can quitting cigarettes lead to depression?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_2.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":3,
                "episodeTitle":"Anxiety Awareness, Panic Attacks, and Pets",
                "episodeDescription":"In this episode I ask you for your reviews and take some wonderful listener questions.First question: What if I am too aware of my anxiety? Second question: How to deal with panic attacks aside from medication?. Third question:Are pets actually beneficial to your mental health?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_3.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":4,
                "episodeTitle":"Ryan on Male Depression, Body Image, and Gaming",
                "episodeDescription":"This is an awesome episode. I welcome my very first guest, Ryan, to the show. He is a buddy of mine from college and we talk about his experiences with depression. I am really happy with this interview because Ryan was so willing to talk candidly and openly about things that just don't seem to be talked about enough in every day life. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_4.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":5,
                "episodeTitle":"Social Anxiety, Recovering from Sexual Abuse, and Migraines",
                "episodeDescription":"First question: What can I do about my social anxiety when I have to interact with important people? Second question: Is there hope for me in recovering from my sexual abuse? Third question: Should I worry about hallucinations that come along with my migraines?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_5.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":6,
                "episodeTitle":"Mike Billstrom on Unexpected Mentors, Overcoming Adve...",
                "episodeDescription":"This episode features a great interview with a new friend, Mike Billstrom from http://theartofgrowth.com. Mike talks about how he had to grow up very quickly to overcome an extremely turbulent upbringing. He found himself in the throes of depression, anxiety, and terrible self-esteem. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_6.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":7,
                "episodeTitle":" Spouse with Depression, Breaking Down Walls, and Getting Over a Breakup",
                "episodeDescription":"First question: How to cope with a severely depressed spouse when you are prone to depression and anxiety yourself? Second question: How to break down the walls that prevent you from truly connecting with other people? Third question: How to 'get over' the loss of a relationship? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_7.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":8,
                "episodeTitle":"Lindsay Istace on Rage Yoga",
                "episodeDescription":"In this episode, I interview Lindsay Istace who is the creator or Rage Yoga (http://rageyoga.com). You have probably heard of Rage Yoga already since it blew up on the news and social media. It is an alternative approach to yoga that strips away the BS and encourages you to release your inner tension through the use of a few choice expletives and 'fist unicorn' additions to your normal yoga poses. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_8.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":9,
                "episodeTitle":"Touch in Therapy, Bringing up Baggage, and Changing Therapists",
                "episodeDescription":"First question: Is it okay to hug your therapist? Second question: WWhen should I bring up my bumpy relationship history with my new partner? Third question:  Should I change therapists?  ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_9.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":10,
                "episodeTitle":"Shannon McFarlin on Talkspace and Internet Therapy",
                "episodeDescription":"This is a super interesting interview! I got a chance to speak to Shannon McFarlin who is a therapist from Talkspace. Talkspace is one of the biggest platforms for internet-based psychotherapy for an affordable price. I do private online therapy, but I was not familiar with larger platforms like Talkspace, so this was totally enlightening for me. I walked away with a very positive impression.",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_10.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":11,
                "episodeTitle":"Impostor Syndrome, Codependency, and Upset Stomach",
                "episodeDescription":"First question:How to overcome the impostor syndrome (feeling like you are a fraud)? Second question: How to have good relationships when you have intense, codependent tendencies? Third question:What you can do about upset stomach with anxiety? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_11.mp3",
                "isCompleted":false,
            },
        ]

    },
    {   "podcastId":"POD3",
        "artist":"Duff the Psych",
        "podcastTitle":"The SelfWork Podcast with Dr. Margaret Rutherford",
        "podcastThumbnail":"https://i.scdn.co/image/340563cb5d1860c1d4e82cb5347dfd8a57ef8593",
        "podcastEpisodes":[
            {
                "episodeNumber":1,
                "episodeTitle":"The Hardcore Self Help Podcast Episode 1",
                "episodeDescription":" First question: Is seven medications for anxiety and depression just crazy? Second question: What's the point of getting extensive testing for dementia? Third question: How to help a family member who has slid back into depression? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_1.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":2,
                "episodeTitle":"Anger, Low Cost Resources, and Cigarettes",
                "episodeDescription":"In this episode, I make a few short announcements and then take a few awesome questions from listeners.First question: How to avoid explosive anger like my dad? Second question: How can I find services without insurance? Third question: Can quitting cigarettes lead to depression?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_2.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":3,
                "episodeTitle":"Anxiety Awareness, Panic Attacks, and Pets",
                "episodeDescription":"In this episode I ask you for your reviews and take some wonderful listener questions.First question: What if I am too aware of my anxiety? Second question: How to deal with panic attacks aside from medication?. Third question:Are pets actually beneficial to your mental health?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_3.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":4,
                "episodeTitle":"Ryan on Male Depression, Body Image, and Gaming",
                "episodeDescription":"This is an awesome episode. I welcome my very first guest, Ryan, to the show. He is a buddy of mine from college and we talk about his experiences with depression. I am really happy with this interview because Ryan was so willing to talk candidly and openly about things that just don't seem to be talked about enough in every day life. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_4.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":5,
                "episodeTitle":"Social Anxiety, Recovering from Sexual Abuse, and Migraines",
                "episodeDescription":"First question: What can I do about my social anxiety when I have to interact with important people? Second question: Is there hope for me in recovering from my sexual abuse? Third question: Should I worry about hallucinations that come along with my migraines?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_5.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":6,
                "episodeTitle":"Mike Billstrom on Unexpected Mentors, Overcoming Adve...",
                "episodeDescription":"This episode features a great interview with a new friend, Mike Billstrom from http://theartofgrowth.com. Mike talks about how he had to grow up very quickly to overcome an extremely turbulent upbringing. He found himself in the throes of depression, anxiety, and terrible self-esteem. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_6.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":7,
                "episodeTitle":" Spouse with Depression, Breaking Down Walls, and Getting Over a Breakup",
                "episodeDescription":"First question: How to cope with a severely depressed spouse when you are prone to depression and anxiety yourself? Second question: How to break down the walls that prevent you from truly connecting with other people? Third question: How to 'get over' the loss of a relationship? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_7.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":8,
                "episodeTitle":"Lindsay Istace on Rage Yoga",
                "episodeDescription":"In this episode, I interview Lindsay Istace who is the creator or Rage Yoga (http://rageyoga.com). You have probably heard of Rage Yoga already since it blew up on the news and social media. It is an alternative approach to yoga that strips away the BS and encourages you to release your inner tension through the use of a few choice expletives and 'fist unicorn' additions to your normal yoga poses. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_8.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":9,
                "episodeTitle":"Touch in Therapy, Bringing up Baggage, and Changing Therapists",
                "episodeDescription":"First question: Is it okay to hug your therapist? Second question: WWhen should I bring up my bumpy relationship history with my new partner? Third question:  Should I change therapists?  ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_9.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":10,
                "episodeTitle":"Shannon McFarlin on Talkspace and Internet Therapy",
                "episodeDescription":"This is a super interesting interview! I got a chance to speak to Shannon McFarlin who is a therapist from Talkspace. Talkspace is one of the biggest platforms for internet-based psychotherapy for an affordable price. I do private online therapy, but I was not familiar with larger platforms like Talkspace, so this was totally enlightening for me. I walked away with a very positive impression.",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_10.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":11,
                "episodeTitle":"Impostor Syndrome, Codependency, and Upset Stomach",
                "episodeDescription":"First question:How to overcome the impostor syndrome (feeling like you are a fraud)? Second question: How to have good relationships when you have intense, codependent tendencies? Third question:What you can do about upset stomach with anxiety? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_11.mp3",
                "isCompleted":false,
            },
        ]

    },
    {   "podcastId":"POD4",
        "artist":"Duff the Psych",
        "podcastTitle":"The Brain Warrior’s Way Podcast",
        "podcastThumbnail":"https://rukminim1.flixcart.com/image/850/1000/ki96c280-0/book/h/b/i/the-brain-warrior-s-way-original-imafy2eup98c57jg.jpeg?q=90",
        "podcastEpisodes":[
            {
                "episodeNumber":1,
                "episodeTitle":"The Hardcore Self Help Podcast Episode 1",
                "episodeDescription":" First question: Is seven medications for anxiety and depression just crazy? Second question: What's the point of getting extensive testing for dementia? Third question: How to help a family member who has slid back into depression? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_1.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":2,
                "episodeTitle":"Anger, Low Cost Resources, and Cigarettes",
                "episodeDescription":"In this episode, I make a few short announcements and then take a few awesome questions from listeners.First question: How to avoid explosive anger like my dad? Second question: How can I find services without insurance? Third question: Can quitting cigarettes lead to depression?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_2.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":3,
                "episodeTitle":"Anxiety Awareness, Panic Attacks, and Pets",
                "episodeDescription":"In this episode I ask you for your reviews and take some wonderful listener questions.First question: What if I am too aware of my anxiety? Second question: How to deal with panic attacks aside from medication?. Third question:Are pets actually beneficial to your mental health?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_3.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":4,
                "episodeTitle":"Ryan on Male Depression, Body Image, and Gaming",
                "episodeDescription":"This is an awesome episode. I welcome my very first guest, Ryan, to the show. He is a buddy of mine from college and we talk about his experiences with depression. I am really happy with this interview because Ryan was so willing to talk candidly and openly about things that just don't seem to be talked about enough in every day life. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_4.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":5,
                "episodeTitle":"Social Anxiety, Recovering from Sexual Abuse, and Migraines",
                "episodeDescription":"First question: What can I do about my social anxiety when I have to interact with important people? Second question: Is there hope for me in recovering from my sexual abuse? Third question: Should I worry about hallucinations that come along with my migraines?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_5.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":6,
                "episodeTitle":"Mike Billstrom on Unexpected Mentors, Overcoming Adve...",
                "episodeDescription":"This episode features a great interview with a new friend, Mike Billstrom from http://theartofgrowth.com. Mike talks about how he had to grow up very quickly to overcome an extremely turbulent upbringing. He found himself in the throes of depression, anxiety, and terrible self-esteem. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_6.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":7,
                "episodeTitle":" Spouse with Depression, Breaking Down Walls, and Getting Over a Breakup",
                "episodeDescription":"First question: How to cope with a severely depressed spouse when you are prone to depression and anxiety yourself? Second question: How to break down the walls that prevent you from truly connecting with other people? Third question: How to 'get over' the loss of a relationship? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_7.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":8,
                "episodeTitle":"Lindsay Istace on Rage Yoga",
                "episodeDescription":"In this episode, I interview Lindsay Istace who is the creator or Rage Yoga (http://rageyoga.com). You have probably heard of Rage Yoga already since it blew up on the news and social media. It is an alternative approach to yoga that strips away the BS and encourages you to release your inner tension through the use of a few choice expletives and 'fist unicorn' additions to your normal yoga poses. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_8.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":9,
                "episodeTitle":"Touch in Therapy, Bringing up Baggage, and Changing Therapists",
                "episodeDescription":"First question: Is it okay to hug your therapist? Second question: WWhen should I bring up my bumpy relationship history with my new partner? Third question:  Should I change therapists?  ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_9.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":10,
                "episodeTitle":"Shannon McFarlin on Talkspace and Internet Therapy",
                "episodeDescription":"This is a super interesting interview! I got a chance to speak to Shannon McFarlin who is a therapist from Talkspace. Talkspace is one of the biggest platforms for internet-based psychotherapy for an affordable price. I do private online therapy, but I was not familiar with larger platforms like Talkspace, so this was totally enlightening for me. I walked away with a very positive impression.",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_10.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":11,
                "episodeTitle":"Impostor Syndrome, Codependency, and Upset Stomach",
                "episodeDescription":"First question:How to overcome the impostor syndrome (feeling like you are a fraud)? Second question: How to have good relationships when you have intense, codependent tendencies? Third question:What you can do about upset stomach with anxiety? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_11.mp3",
                "isCompleted":false,
            },
        ]

    },
    {   "podcastId":"POD5",
        "artist":"Duff the Psych",
        "podcastTitle":"Tell Me What You're Proud Of with Dr. Maggie Perry",
        "podcastThumbnail":"https://s3-us-west-2.amazonaws.com/anchor-generated-image-bank/production/podcast_uploaded_nologo400/2848976/2848976-1583127394747-26c682b830025.jpg",
        "podcastEpisodes":[
            {
                "episodeNumber":1,
                "episodeTitle":"The Hardcore Self Help Podcast Episode 1",
                "episodeDescription":" First question: Is seven medications for anxiety and depression just crazy? Second question: What's the point of getting extensive testing for dementia? Third question: How to help a family member who has slid back into depression? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_1.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":2,
                "episodeTitle":"Anger, Low Cost Resources, and Cigarettes",
                "episodeDescription":"In this episode, I make a few short announcements and then take a few awesome questions from listeners.First question: How to avoid explosive anger like my dad? Second question: How can I find services without insurance? Third question: Can quitting cigarettes lead to depression?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_2.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":3,
                "episodeTitle":"Anxiety Awareness, Panic Attacks, and Pets",
                "episodeDescription":"In this episode I ask you for your reviews and take some wonderful listener questions.First question: What if I am too aware of my anxiety? Second question: How to deal with panic attacks aside from medication?. Third question:Are pets actually beneficial to your mental health?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_3.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":4,
                "episodeTitle":"Ryan on Male Depression, Body Image, and Gaming",
                "episodeDescription":"This is an awesome episode. I welcome my very first guest, Ryan, to the show. He is a buddy of mine from college and we talk about his experiences with depression. I am really happy with this interview because Ryan was so willing to talk candidly and openly about things that just don't seem to be talked about enough in every day life. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_4.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":5,
                "episodeTitle":"Social Anxiety, Recovering from Sexual Abuse, and Migraines",
                "episodeDescription":"First question: What can I do about my social anxiety when I have to interact with important people? Second question: Is there hope for me in recovering from my sexual abuse? Third question: Should I worry about hallucinations that come along with my migraines?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_5.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":6,
                "episodeTitle":"Mike Billstrom on Unexpected Mentors, Overcoming Adve...",
                "episodeDescription":"This episode features a great interview with a new friend, Mike Billstrom from http://theartofgrowth.com. Mike talks about how he had to grow up very quickly to overcome an extremely turbulent upbringing. He found himself in the throes of depression, anxiety, and terrible self-esteem. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_6.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":7,
                "episodeTitle":" Spouse with Depression, Breaking Down Walls, and Getting Over a Breakup",
                "episodeDescription":"First question: How to cope with a severely depressed spouse when you are prone to depression and anxiety yourself? Second question: How to break down the walls that prevent you from truly connecting with other people? Third question: How to 'get over' the loss of a relationship? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_7.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":8,
                "episodeTitle":"Lindsay Istace on Rage Yoga",
                "episodeDescription":"In this episode, I interview Lindsay Istace who is the creator or Rage Yoga (http://rageyoga.com). You have probably heard of Rage Yoga already since it blew up on the news and social media. It is an alternative approach to yoga that strips away the BS and encourages you to release your inner tension through the use of a few choice expletives and 'fist unicorn' additions to your normal yoga poses. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_8.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":9,
                "episodeTitle":"Touch in Therapy, Bringing up Baggage, and Changing Therapists",
                "episodeDescription":"First question: Is it okay to hug your therapist? Second question: WWhen should I bring up my bumpy relationship history with my new partner? Third question:  Should I change therapists?  ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_9.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":10,
                "episodeTitle":"Shannon McFarlin on Talkspace and Internet Therapy",
                "episodeDescription":"This is a super interesting interview! I got a chance to speak to Shannon McFarlin who is a therapist from Talkspace. Talkspace is one of the biggest platforms for internet-based psychotherapy for an affordable price. I do private online therapy, but I was not familiar with larger platforms like Talkspace, so this was totally enlightening for me. I walked away with a very positive impression.",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_10.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":11,
                "episodeTitle":"Impostor Syndrome, Codependency, and Upset Stomach",
                "episodeDescription":"First question:How to overcome the impostor syndrome (feeling like you are a fraud)? Second question: How to have good relationships when you have intense, codependent tendencies? Third question:What you can do about upset stomach with anxiety? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_11.mp3",
                "isCompleted":false,
            },
        ]

    },
    {   "podcastId":"POD6",
        "artist":"Duff the Psych",
        "podcastTitle":"Happier Podcast with Gretchen Rubin",
        "podcastThumbnail":"https://i.scdn.co/image/ab6765630000ba8a1d971613512218740199a755",
        "podcastEpisodes":[
            {
                "episodeNumber":1,
                "episodeTitle":"The Hardcore Self Help Podcast Episode 1",
                "episodeDescription":" First question: Is seven medications for anxiety and depression just crazy? Second question: What's the point of getting extensive testing for dementia? Third question: How to help a family member who has slid back into depression? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_1.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":2,
                "episodeTitle":"Anger, Low Cost Resources, and Cigarettes",
                "episodeDescription":"In this episode, I make a few short announcements and then take a few awesome questions from listeners.First question: How to avoid explosive anger like my dad? Second question: How can I find services without insurance? Third question: Can quitting cigarettes lead to depression?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_2.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":3,
                "episodeTitle":"Anxiety Awareness, Panic Attacks, and Pets",
                "episodeDescription":"In this episode I ask you for your reviews and take some wonderful listener questions.First question: What if I am too aware of my anxiety? Second question: How to deal with panic attacks aside from medication?. Third question:Are pets actually beneficial to your mental health?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_3.mp3",
                "isCompleted":false,
            },
            {
                "episodeNumber":4,
                "episodeTitle":"Ryan on Male Depression, Body Image, and Gaming",
                "episodeDescription":"This is an awesome episode. I welcome my very first guest, Ryan, to the show. He is a buddy of mine from college and we talk about his experiences with depression. I am really happy with this interview because Ryan was so willing to talk candidly and openly about things that just don't seem to be talked about enough in every day life. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_4.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":5,
                "episodeTitle":"Social Anxiety, Recovering from Sexual Abuse, and Migraines",
                "episodeDescription":"First question: What can I do about my social anxiety when I have to interact with important people? Second question: Is there hope for me in recovering from my sexual abuse? Third question: Should I worry about hallucinations that come along with my migraines?",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_5.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":6,
                "episodeTitle":"Mike Billstrom on Unexpected Mentors, Overcoming Adve...",
                "episodeDescription":"This episode features a great interview with a new friend, Mike Billstrom from http://theartofgrowth.com. Mike talks about how he had to grow up very quickly to overcome an extremely turbulent upbringing. He found himself in the throes of depression, anxiety, and terrible self-esteem. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_6.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":7,
                "episodeTitle":" Spouse with Depression, Breaking Down Walls, and Getting Over a Breakup",
                "episodeDescription":"First question: How to cope with a severely depressed spouse when you are prone to depression and anxiety yourself? Second question: How to break down the walls that prevent you from truly connecting with other people? Third question: How to 'get over' the loss of a relationship? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_7.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":8,
                "episodeTitle":"Lindsay Istace on Rage Yoga",
                "episodeDescription":"In this episode, I interview Lindsay Istace who is the creator or Rage Yoga (http://rageyoga.com). You have probably heard of Rage Yoga already since it blew up on the news and social media. It is an alternative approach to yoga that strips away the BS and encourages you to release your inner tension through the use of a few choice expletives and 'fist unicorn' additions to your normal yoga poses. ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_8.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":9,
                "episodeTitle":"Touch in Therapy, Bringing up Baggage, and Changing Therapists",
                "episodeDescription":"First question: Is it okay to hug your therapist? Second question: WWhen should I bring up my bumpy relationship history with my new partner? Third question:  Should I change therapists?  ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_9.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":10,
                "episodeTitle":"Shannon McFarlin on Talkspace and Internet Therapy",
                "episodeDescription":"This is a super interesting interview! I got a chance to speak to Shannon McFarlin who is a therapist from Talkspace. Talkspace is one of the biggest platforms for internet-based psychotherapy for an affordable price. I do private online therapy, but I was not familiar with larger platforms like Talkspace, so this was totally enlightening for me. I walked away with a very positive impression.",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_10.mp3",
                "isCompleted":false,
            },{
                "episodeNumber":11,
                "episodeTitle":"Impostor Syndrome, Codependency, and Upset Stomach",
                "episodeDescription":"First question:How to overcome the impostor syndrome (feeling like you are a fraud)? Second question: How to have good relationships when you have intense, codependent tendencies? Third question:What you can do about upset stomach with anxiety? ",
                "episodeURL":"https://podcastseriesselfhelp.s3.ap-south-1.amazonaws.com/podcast/Episode_11.mp3",
                "isCompleted":false,
            },
        ]

    },
]