export default [
    {   "podcast_id":1,
        "artist":"Artist Name",
        "podcastTitle":"Podcast Title",
        "podcastDescription":"Podcast description",
        "thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
        "podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
    },
    {   "podcast_id":2,
        "artist":"Artist Name",
        "podcastTitle":"Podcast Title",
        "podcastDescription":"Podcast description",
        "thumbnail":"https://i.pinimg.com/564x/b9/6d/01/b96d01c81571b9049166b956308b9e1d.jpg",
        "podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
    },
    {   "podcast_id":3,
        "artist":"Artist Name",
        "podcastTitle":"Some Podcast Title",
        "podcastDescription":"The waveformUrl prop should be a URL to an image of the audio waveform. The library provides a script to generate this image from an audio file.",
        "thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
        "podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
    },
    {   "podcast_id":4,
        "artist":"Artist Name",
        "podcastTitle":"Some Podcast Title",
        "podcastDescription":"The waveformUrl prop should be a URL to an image of the audio waveform. The library provides a script to generate this image from an audio file.",
        "thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
        "podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
    },
    {   "podcast_id":5,
        "artist":"Artist Name",
        "podcastTitle":"Some Podcast Title",
        "podcastDescription":"The waveformUrl prop should be a URL to an image of the audio waveform. The library provides a script to generate this image from an audio file.",
        "thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
        "podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
    },
    {   "podcast_id":6,
    "artist":"Artist Name",
    "podcastTitle":"Some Podcast Title",
    "podcastDescription":"The waveformUrl prop should be a URL to an image of the audio waveform. The library provides a script to generate this image from an audio file.",
    "thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
    "podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
},
{   "podcast_id":7,
"artist":"Artist Name",
"podcastTitle":"Some Podcast Title",
"podcastDescription":"The waveformUrl prop should be a URL to an image of the audio waveform. The library provides a script to generate this image from an audio file.",
"thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
"podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
},
{   "podcast_id":8,
"artist":"Artist Name",
"podcastTitle":"Some Podcast Title",
"podcastDescription":"The waveformUrl prop should be a URL to an image of the audio waveform. The library provides a script to generate this image from an audio file.",
"thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
"podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
},
{"podcast_id":9,
"artist":"Artist Name",
"podcastTitle":"Some Podcast Title",
"podcastDescription":"The waveformUrl prop should be a URL to an image of the audio waveform. The library provides a script to generate this image from an audio file.",
"thumbnail":"https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9kY2FzdHxlbnwwfHwwfHw%3D&w=1000&q=80",
"podcastURL":"https://www.pagalworld.com.se/files/download/id/64630",
}, 
]